services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5657:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  mage:
    build:
      context: ./mage
      dockerfile: Dockerfile
    container_name: mage
    command: mage start project
    ports:
      - "6790:6789"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-db}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - DEFAULT_OWNER_EMAIL=admin@admin.com
      - DEFAULT_OWNER_PASSWORD=admin
    volumes:
      - ./mage/project:/home/src/project
      - ./data:/home/src/data:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - network

volumes:
  postgres_data:
    driver: local

networks:
  network:
    driver: bridge
